/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy):  6. 8.2021   Time (hh:mm): 16:36                        */
/*******************************************************************************/


#ifndef _ASL110_DISPLAY_DEMO_SPECIFICATIONS_H_
#define _ASL110_DISPLAY_DEMO_SPECIFICATIONS_H_

#include "gx_api.h"

/* Determine if C++ compiler is being used, if so use standard C.              */
#ifdef __cplusplus
extern   "C" {
#endif

/* Define widget ids                                                           */

#define ATTENDANT_SETTINGS_SCREEN_ID 1
#define ACTIVE_PROMPT_ID 2
#define PROPORTIONAL_PROMPT_ID 3
#define OVERRIDE_PROMPT_ID 4
#define NEXT_PROFILE_PROMPT_ID 5
#define OK_BTN_ID 6
#define ACTIVE_TOGGLE_BTN_ID 7
#define PROPORTIONAL_TOGGLE_BTN_ID 8
#define OVERRIDE_TOGGLE_BTN_ID 9
#define NEXT_PROFILE_TOGGLE_BTN 10
#define ATTENDANT_DRIVER_ID 11
#define STOP_BUTTON_ID 12
#define DISTANCE_PROMPT_ID 13
#define RAW_POSITION_PROMPT_ID 14
#define DRIVE_DEMAND_PROMPT_ID 15
#define OUTPUT_DEMAND_PROMPT_ID 16
#define FEATURE_SETTINGS_SCREEN_ID 17
#define FEATURE_LIST_BOX_ID 18
#define MAIN_USER_SCREEN_ID 19
#define FIRST_ICON 20
#define FIRST_PROMPT 21
#define FOURTH_ICON 22
#define FOURTH_PROMPT 23
#define SECOND_ICON 24
#define SECOND_PROMPT 25
#define THIRD_ICON 26
#define THIRD_PROMPT 27
#define BOTH_ARROW_BTN_ID 28
#define Fifth_ICON 29
#define FIFTH_PROMPT 30
#define ATTENDANT_BTN_ID 31
#define RESET_SCREEN_FINISH_ID 32
#define CONTINUE_BTN_ID 33
#define PROMPT1_ID 34
#define PROMPT2_ID 35
#define PROMPT3_ID 36
#define PROMPT4_ID 37
#define MINIMUM_DRIVE_SCREEN_ID 38
#define PROMPT_SET_MINIMUM_SPEED 39
#define RIGHT_PAD_PERCENTAGE_BTN_ID 40
#define LEFT_PAD_PERCENTAGE_BTN_ID 41
#define CENTER_PAD_PERCENTAGE_BTN_ID 42
#define PROMPT_FOR_EACH_PAD 43
#define PERFORMANCE_SELECTION_SCREEN_ID 44
#define VEER_ADJUST_BTN_ID 45
#define ATTENDANT_SETTING_BTN_ID 46
#define RESET_SCREEN_ID 47
#define PROMPT_ID 48
#define MORE_SELECTION_SCREEN_ID 49
#define GOTO_DIAGNOSTICS_BTN_ID 50
#define GOTO_RESET_SCREEN_BTN_ID 51
#define HEAD_ARRAY_VERSION_PROMPT_ID 52
#define DISPLAY_VERSION_PROMPT_ID 53
#define USER_SELECTION_SCREEN_ID 54
#define USER_SETTINGS_BTN_ID 55
#define FEATURE_BTN_ID 56
#define PERFORMANCE_BTN_ID 57
#define PERF_ATTEND_BTN_ID 58
#define VEER_ADJUST_SCREEN_ID 59
#define VEER_SLIDER_ID 60
#define SLIDE_VALUE_BUTTON 61
#define OON_SCREEN_ID 62
#define RELEASE_PAD_BUTTON_ID 63
#define READY_SCREEN_ID 64
#define POWER_LARGE_PROMPT_ID 65
#define STARTUP_SPLASH_SCREEN 66
#define CALIBRATION_SCREEN_ID 67
#define CENTER_PAD_ON_BTN_ID 68
#define MINIMUM_INSTRUCT_PROMPT_ID 69
#define LEFT_PAD_ON_BTN_ID 70
#define RIGHT_PAD_ON_BTN_ID 71
#define MAXIMUM_INSTRUCT_PROMPT_ID 72
#define VALUE_PROMPT_ID 73
#define PAD_VALUE_PROMPT_ID 74
#define POWER_PROMPT_ID 75
#define BLUETOOTH_PROMPT_ID 76
#define NEXT_FUNCTION_PROMPT_ID 77
#define POWER_TOGGLE_BTN 78
#define BLUETOOTH_TOGGLE_BTN 79
#define NEXT_FUNCTION_TOGGLE_BTN 80
#define SET_PAD_DIRECTION_SCREEN_ID 81
#define CENTER_PAD_FORWARD_ARROW_BTN_ID 82
#define LEFT_PAD_LEFT_ARROW_BTN_ID 83
#define RIGHT_PAD_RIGHT_ARROW_BTN_ID 84
#define SETTING_PROMPT01_ID 85
#define LEFT_PAD_RIGHT_ARROW_BTN_ID 86
#define LEFT_PAD_FORWARD_ARROW_BTN_ID 87
#define LEFT_PAD_OFF_BTN_ID 88
#define RIGHT_PAD_LEFT_ARROW_BTN_ID 89
#define RIGHT_PAD_FORWARD_ARROW_BTN_ID 90
#define RIGHT_PAD_OFF_BTN_ID 91
#define CENTER_PAD_LEFT_ARROW_BTN_ID 92
#define CENTER_PAD_RIGHT_ARROW_BTN_ID 93
#define CENTER_PAD_OFF_BTN_ID 94
#define PAD_SETTINGS_SCREEN_ID 95
#define PAD_TYPE_BTN_ID 96
#define PAD_DIRECTIONS_BTN_ID 97
#define MINIMUM_DRIVE_BTN_ID 98
#define USER_SETTINGS_SCREEN_ID 99
#define CLICKS_PROMPT_ID 100
#define TIMER_OFF_BTN_ID 101
#define TIMEOUT_PROMPT_ID 102
#define POWERUP_IDLE_PROMPT_ID 103
#define TIMEOUT_BTN_ID 104
#define RNET_ACTIVE_PROMPT_ID 105
#define CLICKS_TOGGLE_BTN 106
#define POWER_UP_TOGGLE_BTN 107
#define RNET_TOGGLE_BTN 108
#define MODE_PORT_SCHEMA_PROMPT_ID 109
#define MODE_SWITCH_SCHEMA_TOGGLE_BTN 110
#define SET_PAD_TYPE_SCREEN_ID 111
#define CENTER_PAD_DIGITAL_BTN_ID 112
#define CENTER_PAD_PROPORTIONAL_BTN_ID 113
#define LEFT_PAD_DIGITAL_BTN_ID 114
#define LEFT_PAD_PROPORTIONAL_BTN_ID 115
#define RIGHT_PAD_DIGITAL_BTN_ID 116
#define RIGHT_PAD_PROPORTIONAL_BTN_ID 117
#define DIAGNOSTIC_SCREEN_ID 118
#define INSTRUCT_PROMPT_ID 119
#define CENTER_PAD_PROP_BTN_ID 120
#define LEFT_PAD_PROP_BTN_ID 121
#define RIGHT_PAD_PROP_BTN_ID 122
#define LEFT_PAD_ADJUSTED_PROMPT 123
#define RIGHT_PAD_ADJUSTED_PROMPT 124
#define CENTER_PAD_ADJUSTED_PROMPT 125
#define USER_PORT_BUTTON 126
#define USER_PORT_PROMPT_DIAG_ID 127
#define MODE_PORT_BUTTON 128
#define Mode_PORT_PROMPT_DIAG_ID 129
#define HH_START_SCREEN_ID 130
#define MORE_BTN_ID 131
#define SETTINGS_BTN_ID 132
#define PAD_SETTINGS_BTN_ID 133
#define UP_ARROW_BTN_ID 134
#define DOWN_ARROW_BTN_ID 135
#define PAD_ACTIVE_BTN_ID 136
#define LONG_PRESS_BUTTON_ID 137


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare properties structures for each utilized widget type                 */

typedef struct GX_STUDIO_WIDGET_STRUCT
{
   GX_CHAR *widget_name;
   USHORT  widget_type;
   USHORT  widget_id;
   #if defined(GX_WIDGET_USER_DATA)
   INT   user_data;
   #endif
   ULONG style;
   ULONG status;
   ULONG control_block_size;
   GX_RESOURCE_ID normal_fill_color_id;
   GX_RESOURCE_ID selected_fill_color_id;
   GX_RESOURCE_ID disabled_fill_color_id;
   UINT (*create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   void (*draw_function) (GX_WIDGET *);
   UINT (*event_function) (GX_WIDGET *, GX_EVENT *);
   GX_RECTANGLE size;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *next_widget;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *child_widget;
   ULONG control_block_offset;
   GX_CONST void *properties;
} GX_STUDIO_WIDGET;

typedef struct
{
    GX_CONST GX_STUDIO_WIDGET *widget_information;
    GX_WIDGET        *widget;
} GX_STUDIO_WIDGET_ENTRY;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_TEXT_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_ML_TEXT_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID unchecked_pixelmap_id;
    GX_RESOURCE_ID checked_pixelmap_id;
    GX_RESOURCE_ID unchecked_disabled_pixelmap_id;
    GX_RESOURCE_ID checked_disabled_pixelmap_id;
} GX_CHECKBOX_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID pixelmap_id;
} GX_ICON_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID normal_pixelmap_id;
    GX_RESOURCE_ID selected_pixelmap_id;
    GX_RESOURCE_ID disabled_pixelmap_id;
} GX_PIXELMAP_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID normal_pixelmap_id;
    GX_RESOURCE_ID selected_pixelmap_id;
} GX_ICON_PROPERTIES;

typedef struct
{
    int min_val;
    int max_val;
    int current_val;
    int increment;
    GX_VALUE min_travel;
    GX_VALUE max_travel;
    GX_VALUE needle_width;
    GX_VALUE needle_height;
    GX_VALUE needle_inset;
    GX_VALUE needle_hotspot;
    GX_RESOURCE_ID lower_pixelmap;
    GX_RESOURCE_ID upper_pixelmap;
    GX_RESOURCE_ID needle_pixelmap;
} GX_PIXELMAP_SLIDER_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    VOID (*format_func)(GX_NUMERIC_PROMPT *, INT);
    INT            numeric_prompt_value;
} GX_NUMERIC_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID left_map_id;
    GX_RESOURCE_ID fill_map_id;
    GX_RESOURCE_ID right_map_id;
    GX_RESOURCE_ID selected_left_map_id;
    GX_RESOURCE_ID selected_fill_map_id;
    GX_RESOURCE_ID selected_right_map_id;
} GX_PIXELMAP_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID wallpaper_id;
} GX_WINDOW_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID wallpaper_id;
    VOID (*callback)(GX_VERTICAL_LIST *, GX_WIDGET *, INT);
    int total_rows;
} GX_VERTICAL_LIST_PROPERTIES;

typedef struct
{
   GX_CONST GX_STUDIO_WIDGET *base_info;
   UINT (*base_create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   GX_RECTANGLE size;
} GX_TEMPLATE_PROPERTIES;


/* Declare top-level control blocks                                            */

typedef struct PRIMARYTEMPLATE_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_PIXELMAP_BUTTON PrimaryTemplate_UpArrowButton;
    GX_PIXELMAP_BUTTON PrimaryTemplate_DownArrowButton;
    GX_TEXT_BUTTON PrimaryTemplate_PadActiveButton;
    GX_TEXT_BUTTON PrimaryTemplate_LongPressButton;
} PRIMARYTEMPLATE_CONTROL_BLOCK;

typedef struct ATTENDANTSETTINGSSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW AttendantSettingsScreen_AttendantSettingsScreenBackdrop;
    GX_PROMPT AttendantSettingsScreen_ActivePrompt;
    GX_PROMPT AttendantSettingsScreen_ProportionalPrompt;
    GX_PROMPT AttendantSettingsScreen_OverridePrompt;
    GX_PROMPT AttendantSettingsScreen_NextProfilePrompt;
    GX_TEXT_BUTTON AttendantSettingsScreen_OK_Button;
    GX_CHECKBOX AttendantSettingsScreen_ActiveToggleBtn;
    GX_CHECKBOX AttendantSettingsScreen_ProportionalToggleBtn;
    GX_CHECKBOX AttendantSettingsScreen_OverrideToggleBtn;
    GX_CHECKBOX AttendantSettingsScreen_NextProfileToggleBtn;
} ATTENDANTSETTINGSSCREEN_CONTROL_BLOCK;

typedef struct ATTENDANTSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW AttendantScreen_AttendantSubScreen;
    GX_ICON AttendantScreen_AttendantDriverControl;
    GX_ICON_BUTTON AttendantScreen_StopButton;
    GX_ICON_BUTTON AttendantScreen_OK_Btn;
    GX_NUMERIC_PROMPT AttendantScreen_Distance_Prompt;
    GX_PROMPT AttendantScreen_RawPosition_Prompt;
    GX_PROMPT AttendantScreen_DriveDemand_Prompt;
    GX_PROMPT AttendantScreen_Output_Demand_Prompt;
} ATTENDANTSCREEN_CONTROL_BLOCK;

typedef struct FEATURESETTINGSSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW FeatureSettingsScreen_UserSettingsScreenBackdrop;
    GX_TEXT_BUTTON FeatureSettingsScreen_OK_Button;
    GX_VERTICAL_LIST FeatureSettingsScreen_FeatureListBox;
    GX_SCROLLBAR FeatureSettingsScreen_FeatureList_vertical_scroll;
} FEATURESETTINGSSCREEN_CONTROL_BLOCK;

typedef struct SCANNER_WINDOW_TEMPLATE_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW Scanner_Window_Template_Scanner_Window;
    GX_ICON Scanner_Window_Template_icon_1;
    GX_ICON Scanner_Window_Template_icon;
    GX_ICON Scanner_Window_Template_icon_2;
    GX_ICON Scanner_Window_Template_icon_3;
    GX_ICON Scanner_Window_Template_icon_4;
    GX_ICON Scanner_Window_Template_icon_5;
    GX_ICON Scanner_Window_Template_icon_6;
    GX_ICON Scanner_Window_Template_icon_7;
} SCANNER_WINDOW_TEMPLATE_CONTROL_BLOCK;

typedef struct MAINUSERSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW MainUserScreen_MainUserScreen_Screen;
    GX_ICON_BUTTON MainUserScreen_FirstIcon;
    GX_PROMPT MainUserScreen_FirstPrompt;
    GX_ICON_BUTTON MainUserScreen_FourthIcon;
    GX_PROMPT MainUserScreen_FourthPrompt;
    GX_ICON_BUTTON MainUserScreen_SecondIcon;
    GX_PROMPT MainUserScreen_SecondPrompt;
    GX_ICON_BUTTON MainUserScreen_ThirdIcon;
    GX_PROMPT MainUserScreen_ThirdPrompt;
    GX_BUTTON MainUserScreen_BothArrowButtonID_VirtualButton;
    GX_ICON_BUTTON MainUserScreen_FifthIcon;
    GX_PROMPT MainUserScreen_FifthPrompt;
    GX_PIXELMAP_BUTTON MainUserScreen_Fusion_Button;
    GX_ICON_BUTTON MainUserScreen_Attendant_Button;
} MAINUSERSCREEN_CONTROL_BLOCK;

typedef struct RESETSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW ResetScreen_ResetScreenBackdrop;
    GX_TEXT_BUTTON ResetScreen_Continue_Button;
    GX_TEXT_BUTTON ResetScreen_OK_Button;
    GX_PROMPT ResetScreen_Prompt1;
    GX_PROMPT ResetScreen_Prompt2;
    GX_PROMPT ResetScreen_Prompt3;
    GX_PROMPT ResetScreen_Prompt4;
    GX_ICON ResetScreen_icon;
} RESETSCREEN_CONTROL_BLOCK;

typedef struct MINIMUMDRIVESCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW MinimumDriveScreen_MinimumDriveScreenBackdrop;
    GX_TEXT_BUTTON MinimumDriveScreen_OK_Button;
    GX_PROMPT MinimumDriveScreen_Prompt_SetMinimumSpeed;
    GX_TEXT_BUTTON MinimumDriveScreen_RightPadPercentage_Button;
    GX_TEXT_BUTTON MinimumDriveScreen_LeftPadPercentage_Button;
    GX_TEXT_BUTTON MinimumDriveScreen_CenterPadPercentage_Button;
    GX_PROMPT MinimumDriveScreen_Prompt_ForEachPad;
} MINIMUMDRIVESCREEN_CONTROL_BLOCK;

typedef struct PERFORMANCESELECTIONSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW PerformanceSelectionScreen_NextPadScreenBackdrop;
    GX_TEXT_BUTTON PerformanceSelectionScreen_OK_Button;
    GX_TEXT_BUTTON PerformanceSelectionScreen_VeerAdjust_Button;
    GX_TEXT_BUTTON PerformanceSelectionScreen_AttendantSetting_Button;
} PERFORMANCESELECTIONSCREEN_CONTROL_BLOCK;

typedef struct RESETFINISHSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW ResetFinishScreen_ResetFinishScreenBackdrop;
    GX_TEXT_BUTTON ResetFinishScreen_OK_Button;
    GX_PROMPT ResetFinishScreen_Prompt;
} RESETFINISHSCREEN_CONTROL_BLOCK;

typedef struct MORESELECTIONSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW MoreSelectionScreen_UserSelectionScreenBackdrop;
    GX_TEXT_BUTTON MoreSelectionScreen_GotoDiagostics_Button;
    GX_TEXT_BUTTON MoreSelectionScreen_GotoResetSettings_lButton;
    GX_TEXT_BUTTON MoreSelectionScreen_OK_Button;
    GX_PROMPT MoreSelectionScreen_HeadArray_VersionPrompt;
    GX_PROMPT MoreSelectionScreen_VersionPrompt;
} MORESELECTIONSCREEN_CONTROL_BLOCK;

typedef struct USERSELECTIONSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW UserSelectionScreen_UserSelectionScreenBackdrop;
    GX_TEXT_BUTTON UserSelectionScreen_UserSettings_Button;
    GX_TEXT_BUTTON UserSelectionScreen_FeatureSettings_lButton;
    GX_TEXT_BUTTON UserSelectionScreen_OK_Button;
    GX_TEXT_BUTTON UserSelectionScreen_Performance_Button;
    GX_MULTI_LINE_TEXT_BUTTON UserSelectionScreen_Performance_Attendant_Button;
} USERSELECTIONSCREEN_CONTROL_BLOCK;

typedef struct VEERADJUSTSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW VeerAdjustScreen_VeerAdjustScreenBackdrop;
    GX_PIXELMAP_SLIDER VeerAdjustScreen_VeerSlider;
    GX_TEXT_BUTTON VeerAdjustScreen_OK_Button;
    GX_TEXT_BUTTON VeerAdjustScreen_SliderValue_Button;
    GX_PROMPT VeerAdjustScreen_InstructionLine_1;
    GX_PROMPT VeerAdjustScreen_InstructionLine_2;
} VEERADJUSTSCREEN_CONTROL_BLOCK;

typedef struct OON_SCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW OON_Screen_OON_Screen_Background;
    GX_PROMPT OON_Screen_ReleasePad_Button;
} OON_SCREEN_CONTROL_BLOCK;

typedef struct READYSCREEN_TEMPLATE_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW ReadyScreen_Template_ReadyScreen;
    GX_PIXELMAP_PROMPT ReadyScreen_Template_PowerLargePrompt;
    GX_PROMPT ReadyScreen_Template_prompt;
} READYSCREEN_TEMPLATE_CONTROL_BLOCK;

typedef struct STARTUPSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW StartupScreen_StartupSplashScreen;
    GX_PIXELMAP_BUTTON StartupScreen_pixelmap_button;
} STARTUPSCREEN_CONTROL_BLOCK;

typedef struct PADCALIBRATIONSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW PadCalibrationScreen_PadScreenBackdrop;
    GX_PIXELMAP_BUTTON PadCalibrationScreen_CenterPadON_Button;
    GX_PROMPT PadCalibrationScreen_MinimumInstructionsText;
    GX_PIXELMAP_BUTTON PadCalibrationScreen_LeftPadON_Button;
    GX_TEXT_BUTTON PadCalibrationScreen_OK_Button;
    GX_PIXELMAP_BUTTON PadCalibrationScreen_RightPadON_Button;
    GX_PROMPT PadCalibrationScreen_MaximumInstructionsText;
    GX_NUMERIC_PROMPT PadCalibrationScreen_Value_Prompt;
    GX_NUMERIC_PROMPT PadCalibrationScreen_PadValue_Prompt;
} PADCALIBRATIONSCREEN_CONTROL_BLOCK;

typedef struct FEATURESETTINGSSCREEN_OLD_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW FeatureSettingsScreen_OLD_UserSettingsScreenBackdrop;
    GX_PROMPT FeatureSettingsScreen_OLD_PowerPrompt;
    GX_PROMPT FeatureSettingsScreen_OLD_BluetoothPrompt;
    GX_PROMPT FeatureSettingsScreen_OLD_NextFunctionPrompt;
    GX_PROMPT FeatureSettingsScreen_OLD_NextProfilePrompt;
    GX_TEXT_BUTTON FeatureSettingsScreen_OLD_OK_Button;
    GX_CHECKBOX FeatureSettingsScreen_OLD_PowerToggleBtn;
    GX_CHECKBOX FeatureSettingsScreen_OLD_BluetoothToggleBtn;
    GX_CHECKBOX FeatureSettingsScreen_OLD_NextFunctionToggleBtn;
    GX_CHECKBOX FeatureSettingsScreen_OLD_NextProfileToggleBtn;
} FEATURESETTINGSSCREEN_OLD_CONTROL_BLOCK;

typedef struct SETPADDIRECTIONSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW SetPadDirectionScreen_SetPadScreenBackdrop;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_CenterPad_ForwardArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_LeftPad_LeftArrow_Button;
    GX_TEXT_BUTTON SetPadDirectionScreen_OK_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_RightPad_RightArrow_Button;
    GX_PROMPT SetPadDirectionScreen_SettingPadPrompt;
    GX_PROMPT SetPadDirectionScreen_SettingPadPrompt_1;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_LeftPad_RightArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_LeftPad_ForwardArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_LeftPad_Off_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_RightPad_LeftArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_RightPad_ForwardArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_RightPad_Off_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_CenterPad_LeftArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_CenterPad_RightArrow_Button;
    GX_PIXELMAP_BUTTON SetPadDirectionScreen_CenterPad_Off_Button;
} SETPADDIRECTIONSCREEN_CONTROL_BLOCK;

typedef struct PADOPTIONSSETTINGSSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW PadOptionsSettingsScreen_PadSettingsScreenBackdrop;
    GX_TEXT_BUTTON PadOptionsSettingsScreen_PadSettings_Button;
    GX_TEXT_BUTTON PadOptionsSettingsScreen_PadDirection_Button;
    GX_TEXT_BUTTON PadOptionsSettingsScreen_OK_Button;
    GX_TEXT_BUTTON PadOptionsSettingsScreen_MinimumDrive_lButton;
} PADOPTIONSSETTINGSSCREEN_CONTROL_BLOCK;

typedef struct USERSETTINGSSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW UserSettingsScreen_UserSettingsScreenBackdrop;
    GX_PROMPT UserSettingsScreen_Clicks_Prompt;
    GX_TEXT_BUTTON UserSettingsScreen_OK_Button;
    GX_PIXELMAP_BUTTON UserSettingsScreen_Timer_Off_Button;
    GX_PROMPT UserSettingsScreen_TImeoutPrompt;
    GX_PROMPT UserSettingsScreen_PowerUpIdle_Prompt;
    GX_TEXT_BUTTON UserSettingsScreen_Timeout_Button;
    GX_PROMPT UserSettingsScreen_RNetActive_Prompt;
    GX_CHECKBOX UserSettingsScreen_ClicksToggleBtn;
    GX_CHECKBOX UserSettingsScreen_PowerUpToggleBtn;
    GX_CHECKBOX UserSettingsScreen_RNET_ToggleBtn;
    GX_PROMPT UserSettingsScreen_ModePortSchema_Prompt;
    GX_CHECKBOX UserSettingsScreen_ModeSwitchSchema_ToggleBtn;
} USERSETTINGSSCREEN_CONTROL_BLOCK;

typedef struct SETPADTYPESCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW SetPadTypeScreen_SetPadScreenBackdrop;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_CenterPadDigital_Button;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_CenterPadProportional_Button;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_LeftPadDigital_Button;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_LeftPadProportional_Button;
    GX_TEXT_BUTTON SetPadTypeScreen_OK_Button;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_RightPadDigital_Button;
    GX_PIXELMAP_BUTTON SetPadTypeScreen_RightPadProportional_Button;
    GX_PROMPT SetPadTypeScreen_SettingPadPrompt;
    GX_PROMPT SetPadTypeScreen_SettingPadPrompt_1;
} SETPADTYPESCREEN_CONTROL_BLOCK;

typedef struct DIAGNOSTICSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW DiagnosticScreen_DiagnosticScreenBackdrop;
    GX_PIXELMAP_BUTTON DiagnosticScreen_CenterPadDigital_Button;
    GX_PROMPT DiagnosticScreen_InstructionsText;
    GX_PIXELMAP_BUTTON DiagnosticScreen_LeftPadDigital_Button;
    GX_TEXT_BUTTON DiagnosticScreen_OK_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_RightPadDigital_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_CenterPadProp_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_LeftPadProp_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_RightPadProp_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_CenterPadOff_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_LeftPadOff_Button;
    GX_PIXELMAP_BUTTON DiagnosticScreen_RightPadOff_Button;
    GX_PROMPT DiagnosticScreen_LeftPad_Adjusted_Prompt;
    GX_PROMPT DiagnosticScreen_RightPad_Adjusted_Prompt;
    GX_PROMPT DiagnosticScreen_CenterPad_Adjusted_Prompt;
    GX_ICON_BUTTON DiagnosticScreen_UserPort_IconButton;
    GX_PROMPT DiagnosticScreen_UserPort_Prompt;
    GX_ICON_BUTTON DiagnosticScreen_ModePort_IconButton;
    GX_PROMPT DiagnosticScreen_ModePort_Prompt;
} DIAGNOSTICSCREEN_CONTROL_BLOCK;

typedef struct HHP_START_SCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_WINDOW HHP_Start_Screen_HHP_Start_Backdrop;
    GX_TEXT_BUTTON HHP_Start_Screen_MainMore_Button;
    GX_TEXT_BUTTON HHP_Start_Screen_Settings_Button;
    GX_TEXT_BUTTON HHP_Start_Screen_OK_Button;
    GX_TEXT_BUTTON HHP_Start_Screen_PadSettings_Button;
} HHP_START_SCREEN_CONTROL_BLOCK;


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern ATTENDANTSETTINGSSCREEN_CONTROL_BLOCK AttendantSettingsScreen;
extern ATTENDANTSCREEN_CONTROL_BLOCK AttendantScreen;
extern FEATURESETTINGSSCREEN_CONTROL_BLOCK FeatureSettingsScreen;
extern SCANNER_WINDOW_TEMPLATE_CONTROL_BLOCK Scanner_Window_Template;
extern MAINUSERSCREEN_CONTROL_BLOCK MainUserScreen;
extern RESETSCREEN_CONTROL_BLOCK ResetScreen;
extern MINIMUMDRIVESCREEN_CONTROL_BLOCK MinimumDriveScreen;
extern PERFORMANCESELECTIONSCREEN_CONTROL_BLOCK PerformanceSelectionScreen;
extern RESETFINISHSCREEN_CONTROL_BLOCK ResetFinishScreen;
extern MORESELECTIONSCREEN_CONTROL_BLOCK MoreSelectionScreen;
extern USERSELECTIONSCREEN_CONTROL_BLOCK UserSelectionScreen;
extern VEERADJUSTSCREEN_CONTROL_BLOCK VeerAdjustScreen;
extern OON_SCREEN_CONTROL_BLOCK OON_Screen;
extern READYSCREEN_TEMPLATE_CONTROL_BLOCK ReadyScreen_Template;
extern STARTUPSCREEN_CONTROL_BLOCK StartupScreen;
extern PADCALIBRATIONSCREEN_CONTROL_BLOCK PadCalibrationScreen;
extern FEATURESETTINGSSCREEN_OLD_CONTROL_BLOCK FeatureSettingsScreen_OLD;
extern SETPADDIRECTIONSCREEN_CONTROL_BLOCK SetPadDirectionScreen;
extern PADOPTIONSSETTINGSSCREEN_CONTROL_BLOCK PadOptionsSettingsScreen;
extern USERSETTINGSSCREEN_CONTROL_BLOCK UserSettingsScreen;
extern SETPADTYPESCREEN_CONTROL_BLOCK SetPadTypeScreen;
extern DIAGNOSTICSCREEN_CONTROL_BLOCK DiagnosticScreen;
extern HHP_START_SCREEN_CONTROL_BLOCK HHP_Start_Screen;
extern PRIMARYTEMPLATE_CONTROL_BLOCK PrimaryTemplate;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT AttendantSettingsScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT AttendantScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT FeatureSettingsScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID FeatureList_callback(GX_VERTICAL_LIST *, GX_WIDGET *, INT);
UINT MainUserScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID MainUserScreen_draw_function(GX_WINDOW *widget);
UINT ResetScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT MinimumDriveScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT PerformanceSelectionScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT ResetFinishScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT MoreSelectionScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT UserSelectionScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT VeerAdjust_Screen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT VeerSlider_event_function(GX_PIXELMAP_SLIDER *widget, GX_EVENT *event_ptr);
VOID Slider_Draw_Function(GX_PIXELMAP_SLIDER *widget);
UINT OON_Window_event_function(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT StartupScreen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID StartScreen_draw_function(GX_WINDOW *widget);
UINT CalibrationScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID CalibrationScreen_draw(GX_WINDOW *widget);
UINT SetPadDirectionScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT PadOptionsSettingsScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT UserSettingsScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT SetPadTypeScreen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT DiagnosticScreen_event_handler(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT HHP_Start_Screen_event_process(GX_WINDOW *widget, GX_EVENT *event_ptr);
UINT Template_event_function(GX_WINDOW *widget, GX_EVENT *event_ptr);

/* Declare the GX_STUDIO_DISPLAY_INFO structure                                */


typedef struct GX_STUDIO_DISPLAY_INFO_STRUCT 
{
    GX_CONST GX_CHAR *name;
    GX_CONST GX_CHAR *canvas_name;
    GX_CONST GX_THEME **theme_table;
    GX_CONST GX_CHAR ***language_table;
    USHORT   theme_table_size;
    USHORT   language_table_size;
    UINT     string_table_size;
    UINT     x_resolution;
    UINT     y_resolution;
    GX_DISPLAY *display;
    GX_CANVAS  *canvas;
    GX_WINDOW_ROOT *root_window;
    GX_COLOR   *canvas_memory;
    ULONG      canvas_memory_size;
} GX_STUDIO_DISPLAY_INFO;


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_multi_line_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_checkbox_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_pixelmap_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_pixelmap_slider_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_numeric_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_pixelmap_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_vertical_list_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_vertical_scrollbar_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_template_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
GX_WIDGET *gx_studio_widget_create(GX_BYTE *storage, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

/* Determine if a C++ compiler is being used.  If so, complete the standard
  C conditional started above.                                                 */
#ifdef __cplusplus
}
#endif

#endif                                       /* sentry                         */
